#### general settings
name: Ours_noT_N3_0921_6_s4
use_tb_logger: false #true
model: VideoSR_base
distortion: sr
scale: 4
gpu_ids: [0]

#### datasets
datasets:
  train:
    name: Adobe_a
    mode: Adobe_a # Adobe & Adobe_a
    interval_list: [1]
    random_reverse: true #false
    border_mode: false
    dataroot_GT: /work/abcd233746pc/frame_without_split/train
    dataroot_LQ: /work/abcd233746pc/frame_without_split/train
    cache_keys: data/Vimeo7_train_keys.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 24
    GT_size: 128
    LQ_size: 32
    use_flip: true
    use_rot: true
    color: RGB

    sample_num: 3

#### network structures
network_G:
  which_model_G: Ours_ZSM # LunaTokis & LIIF
  nf: 64
  nframes: 7
  groups: 8
  front_RBs: 5
  mid_RBs: 0
  back_RBs: 40
  HR_in: false
  setting: 6

#### path
path:
  pretrain_model_G: /home/abcd233746pc/VideoINR-Continuous-Space-Time-Super-Resolution/saved_checkpoints/Ours_noT_N3_0921_6_s4/450000_G.pth
  strict_load: true #true #
  resume_state: /home/abcd233746pc/VideoINR-Continuous-Space-Time-Super-Resolution/saved_checkpoints/Ours_noT_N3_0921_6_s4/450000.state
  models: /home/abcd233746pc/VideoINR-Continuous-Space-Time-Super-Resolution/saved_checkpoints/Ours_noT_N3_0921_6_s4/
  training_state: /home/abcd233746pc/VideoINR-Continuous-Space-Time-Super-Resolution/saved_checkpoints/Ours_noT_N3_0921_6_s4/
  root: ./

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  warmup_iter: -1 #4000  # -1: no warm up
  T_period: [150000, 150000, 150000, 150000]
  restarts: [150000, 300000, 450000]
  restart_weights: [1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3